# example netlify.toml
[build]
  base = "."
  command = """
    cd examples/langchain-cdp-chatbot && npm install && npm run build
  """
  publish = "examples/langchain-cdp-chatbot/dist"
  functions = "examples/langchain-cdp-chatbot/dist/netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  CI = "false"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["express", "socket.io", "@coinbase/agentkit", "@coinbase/agentkit-langchain"]
  included_files = [
    "examples/langchain-cdp-chatbot/public/**",
    "agentkit/dist/**",
    "framework-extensions/langchain/dist/**"
  ]
  node_bundler = "esbuild"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
